# Transforming

In [149]:
data = z_df.set_index('full_species')
data.head()

                                NE_MEDIAN      z_pi  z_cm_per_mb      z_ne
full_species
Allenopithecus_nigroviridis  48795.239046  0.035514    -0.820631 -0.330025
Allenopithecus_nigroviridis  48795.239046  0.036663     0.266051 -0.330025
Allenopithecus_nigroviridis  48795.239046  0.849468    -0.166861 -0.330025
Allenopithecus_nigroviridis  48795.239046 -0.093303    -0.572792 -0.330025
Allenopithecus_nigroviridis  48795.239046 -0.149338     0.097297 -0.330025

In [153]:
trans_cols = ['corrected_pi', 'cm_per_mb', 'z_cm_per_mb']
extra_cols = ['NE_MEDIAN']

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data_index = data.index
zdata = pd.concat([pd.DataFrame(scaler.fit_transform(df[trans_cols]), 
                                columns=trans_cols, index=data_index),
                  data[extra_cols]],
                  axis=1
                 )
zdata.head()

                                 z_pi      z_ne  z_cm_per_mb     NE_MEDIAN
full_species
Allenopithecus_nigroviridis  0.035515 -0.330025    -0.820657  48795.239046
Allenopithecus_nigroviridis  0.036664 -0.330025     0.266060  48795.239046
Allenopithecus_nigroviridis  0.849495 -0.330025    -0.166867  48795.239046
Allenopithecus_nigroviridis -0.093306 -0.330025    -0.572810  48795.239046
Allenopithecus_nigroviridis -0.149343 -0.330025     0.097300  48795.239046

In [155]:
# do some modelling and get back posterior estimates
ar = zdata[cols].to_numpy() # dummy vars
pd.concat([pd.DataFrame(scaler.inverse_transform(ar), columns=cols, index=data_index),
                  data[extra_cols]],
                  axis=1
                 )

                                 z_pi      z_ne  z_cm_per_mb     NE_MEDIAN
full_species
Allenopithecus_nigroviridis  0.035514 -0.330025    -0.820631  48795.239046
Allenopithecus_nigroviridis  0.036663 -0.330025     0.266051  48795.239046
Allenopithecus_nigroviridis  0.849468 -0.330025    -0.166861  48795.239046
Allenopithecus_nigroviridis -0.093303 -0.330025    -0.572792  48795.239046
Allenopithecus_nigroviridis -0.149338 -0.330025     0.097297  48795.239046
...                               ...       ...          ...           ...
Varecia_variegata            0.638573 -0.075719    -0.098736  65217.078027
Varecia_variegata            0.415710 -0.075719    -0.891264  65217.078027
Varecia_variegata            0.885051 -0.075719    -0.850514  65217.078027
Varecia_variegata            0.358877 -0.075719    -0.918883  65217.078027
Varecia_variegata           -1.306729 -0.075719    -0.938086  65217.078027

[2940166 rows x 4 columns]

In [123]:
data = z_df
cols = ['z_pi', 'z_ne']
index_cols = ['full_species', 'NE_MEDIAN']

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

data_index = data.set_index(index_cols).index
zdata = pd.DataFrame(scaler.fit_transform(df[cols]), columns=cols, index=index).reset_index()
zdata.head()

                  full_species     NE_MEDIAN      z_pi      z_ne
0  Allenopithecus_nigroviridis  48795.239046  0.035515 -0.330025
1  Allenopithecus_nigroviridis  48795.239046  0.036664 -0.330025
2  Allenopithecus_nigroviridis  48795.239046  0.849495 -0.330025
3  Allenopithecus_nigroviridis  48795.239046 -0.093306 -0.330025
4  Allenopithecus_nigroviridis  48795.239046 -0.149343 -0.330025